// Test suite for ph config wizard
import { describe, it, expect } from "vitest";
import {
  mkdirSync,
  writeFileSync,
  readFileSync,
  existsSync,
  rmSync,
} from "node:fs";
import { join } from "node:path";

// Import generateConfigContent for unit testing
import { generateConfigContent } from "../src/cli/commands/config-wizard.js";

function getTestDir(): string {
  const dir = join(process.cwd(), `.test-config-wizard-${Date.now()}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

describe("Config Wizard: generateConfigContent", () => {
  it("generates valid config with all modules enabled", () => {
    const content = generateConfigContent({
      enabledModules: [
        "cicd",
        "quality",
        "docs",
        "flakiness",
        "security",
        "prComplexity",
        "env",
        "buildPerf",
      ],
      weights: {
        cicd: 15,
        quality: 18,
        docs: 6,
        flakiness: 14,
        security: 20,
        prComplexity: 4,
        env: 13,
        buildPerf: 10,
      },
      complexityThreshold: 10,
      failUnder: 70,
      failUnderRaw: 70,
      flakinessPassRate: 95,
      snykToken: "",
      watchModeDefault: false,
    });

    expect(content).toContain("Auto-generated by ph config wizard");
    expect(content).toContain("cicd:");
    expect(content).toContain("quality:");
    expect(content).toContain("enabled: true");
    expect(content).toContain("failUnder: 70");
    expect(content).toContain("passRateThreshold: 0.95");
    expect(content).toContain("complexityThreshold: 10");
  });

  it("disables unchecked modules", () => {
    const content = generateConfigContent({
      enabledModules: ["quality", "security"],
      weights: { quality: 50, security: 50 },
      complexityThreshold: 10,
      failUnder: 0,
      failUnderRaw: 0,
      flakinessPassRate: 95,
      snykToken: "",
      watchModeDefault: false,
    });

    // Disabled modules should have enabled: false
    expect(content).toContain("cicd:");
    // Find the cicd block - it should have enabled: false
    const cicdMatch = content.match(
      /cicd:\s*\{[\s\S]*?enabled:\s*(true|false)/,
    );
    expect(cicdMatch).toBeTruthy();
    expect(cicdMatch![1]).toBe("false");

    // Enabled modules should have enabled: true
    const qualityMatch = content.match(
      /quality:\s*\{[\s\S]*?enabled:\s*(true|false)/,
    );
    expect(qualityMatch).toBeTruthy();
    expect(qualityMatch![1]).toBe("true");
  });

  it("includes Snyk token when provided", () => {
    const content = generateConfigContent({
      enabledModules: ["security"],
      weights: { security: 100 },
      complexityThreshold: 10,
      failUnder: 0,
      failUnderRaw: 0,
      flakinessPassRate: 95,
      snykToken: "my-snyk-token-123",
      watchModeDefault: false,
    });

    expect(content).toContain('snykToken: "my-snyk-token-123"');
  });

  it("leaves Snyk token empty when not provided", () => {
    const content = generateConfigContent({
      enabledModules: ["security"],
      weights: { security: 100 },
      complexityThreshold: 10,
      failUnder: 0,
      failUnderRaw: 0,
      flakinessPassRate: 95,
      snykToken: "",
      watchModeDefault: false,
    });

    expect(content).toContain('snykToken: ""');
  });

  it("sets failUnder to 0 when CI gate is disabled", () => {
    const content = generateConfigContent({
      enabledModules: ["quality"],
      weights: { quality: 100 },
      complexityThreshold: 10,
      failUnder: 0,
      failUnderRaw: 0,
      flakinessPassRate: 95,
      snykToken: "",
      watchModeDefault: false,
    });

    expect(content).toContain("failUnder: 0");
  });

  it("sets passRateThreshold as decimal", () => {
    const content = generateConfigContent({
      enabledModules: ["flakiness"],
      weights: { flakiness: 100 },
      complexityThreshold: 10,
      failUnder: 0,
      failUnderRaw: 0,
      flakinessPassRate: 90,
      snykToken: "",
      watchModeDefault: false,
    });

    expect(content).toContain("passRateThreshold: 0.9");
  });

  it("includes all 8 module weight entries", () => {
    const content = generateConfigContent({
      enabledModules: [
        "cicd",
        "quality",
        "docs",
        "flakiness",
        "security",
        "prComplexity",
        "env",
        "buildPerf",
      ],
      weights: {
        security: 20,
        quality: 18,
        cicd: 15,
        flakiness: 14,
        env: 13,
        buildPerf: 10,
        docs: 6,
        prComplexity: 4,
      },
      complexityThreshold: 10,
      failUnder: 60,
      failUnderRaw: 60,
      flakinessPassRate: 95,
      snykToken: "",
      watchModeDefault: false,
    });

    expect(content).toContain("security: 20");
    expect(content).toContain("quality: 18");
    expect(content).toContain("cicd: 15");
    expect(content).toContain("flakiness: 14");
    expect(content).toContain("env: 13");
    expect(content).toContain("buildPerf: 10");
    expect(content).toContain("docs: 6");
    expect(content).toContain("prComplexity: 4");
  });

  it("weights that don't sum to 100 get normalized", () => {
    // If weights sum to 90, they should be auto-normalized
    const content = generateConfigContent({
      enabledModules: ["quality", "security"],
      weights: { quality: 40, security: 50 }, // totals 90
      complexityThreshold: 10,
      failUnder: 0,
      failUnderRaw: 0,
      flakinessPassRate: 95,
      snykToken: "",
      watchModeDefault: false,
    });

    // Config still generates (normalization happens in wizard, not in generateConfigContent)
    expect(content).toContain("quality:");
    expect(content).toContain("security:");
  });

  it("config content can be written to file and read back", () => {
    const TEST_DIR = getTestDir();
    const content = generateConfigContent({
      enabledModules: ["quality"],
      weights: { quality: 100 },
      complexityThreshold: 15,
      failUnder: 80,
      failUnderRaw: 80,
      flakinessPassRate: 90,
      snykToken: "",
      watchModeDefault: true,
    });

    const configPath = join(TEST_DIR, "project-health.config.ts");
    writeFileSync(configPath, content, "utf-8");

    expect(existsSync(configPath)).toBe(true);
    const readBack = readFileSync(configPath, "utf-8");
    expect(readBack).toContain("complexityThreshold: 15");
    expect(readBack).toContain("failUnder: 80");
  });

  it("handles zero weights gracefully", () => {
    const content = generateConfigContent({
      enabledModules: ["cicd", "quality"],
      weights: { cicd: 0, quality: 100 },
      complexityThreshold: 10,
      failUnder: 0,
      failUnderRaw: 0,
      flakinessPassRate: 95,
      snykToken: "",
      watchModeDefault: false,
    });

    expect(content).toContain("cicd: 0");
    expect(content).toContain("quality: 100");
  });
});
